devpi-server:
  serverdir: <%= scope['devpi::server_dir'] %>
  secretfile: <%= scope['devpi::confif_dir'] %>/secret
  host: <%= scope['devpi::listen_host'] %>
  port: <%= scope['devpi::listen_port'] %>
devpi-ldap:
  url: <%= scope['devpi::ldap_connection'] %>
  user_template: <%= scope['devpi::ldap_user_filter'] %>
  group_search:
    base: <%= scope['devpi::ldap_group_base'] %>
    filter: <%= scope['devpi::ldap_group_filter'] %>
    attribute_name: <%= scope['devpi::ldap_group_attr'] %>